o Simplified the ResourcesMojo to eliminate the need for a ResourceEntry class, which is easily replaced by usage of a TreeMap (avoid the NoClassDefFoundError from before SEE MNG-243) o Changed the references to repo1.maven.org for central repository to repo1.maven.org/maven2 in preparation for switchover to ibiblio.org
    This will allow us to transparently switch between redirects and CNAME changes for referencing ibiblio.org, since ibiblio will not allow a
    vhost for m2 or a rewrite rule...switching the URL for the repo will allow changes to the CNAME (satisfy ibiblio's pathing) while at the same
    time allowing the use of redirects (redirect can be at /maven2/index.html rather than /index.html, f.e.).


git-svn-id: https://svn.apache.org/repos/asf/maven/components/trunk/maven-core@163772 13f79535-47bb-0310-9956-ffa450edef68